### PR TITLE
net-im/rambox-bin: correct and unmask 0.5.8 version

### PR DESCRIPTION
**Pull request by Cynede**

### CODE REVIEW

**Comment by Cogitri** [comment]
0.5.8 is a pre-release, so I would rather not unmask it for now ( open for suggestions though )

**Comment by Cynede** [comment]
@Keepco ~ is unstable arch :)

**Comment by Cogitri** [comment]
Yeah, it is unstable, but because this is an unofficial overlay everything is ~. If I just unmask pre-releases they don't differ from normal releases ( and users who already use unstable rambox-bin ebuilds would be upgraded to a pre-release ), so I'd like to avoid that

**Comment by Cynede** [comment]
well okay but I'm lazy to unmask things in accept keywords usually :P

**Pull request merged**
