### PR TITLE
Bump GitKraken; modify ebuild to meet new binary requirements

### PR DESCRIPTION
**Pull request by evanjs**
- Bump GitKraken ebuild to 3.1.0
- Add dosym to src_install in GitKraken ebuild.  Around 3.0.1, GitKraken started looking for libcurl-gnutls.so.4 and failed to start if the library could not be found
- Update GitKraken manifest for version bump

No idea if the dosym is bad practice or could be done better, but GitKraken runs, and I'm able to push/pull.

### CODE REVIEW

**Comment by Cogitri** [comment]
I guess it would be a good idea to run `dosym /usr/$(get_libdir)/libcurl.so.4 /usr/$(get_libdir)/libcurl-gnutls.so.4` instead, but other than that it looks good to me. For future contributions: Please follow the commit message scheme I use ( categorie/packagename: change )

**Comment by evanjs** [comment]
Ah, didn't see that.  Will do. Also, I did try /usr/$(get_libdir), but ran into this [issue](https://dev.gentoo.org/~zmedico/portage/doc/ch07s06.html).  Worked fine with a relative path.

**Comment by Cogitri** [comment]
Oh, didn't know about that, thanks for bringing that to my attention! :)

**Comment by Cogitri** [comment]
Also, thanks for the contribution!

**Pull request merged**
